trigger:
  branches:
    include:
      - master  # O la rama de tu preferencia

pool:
  vmImage: 'ubuntu-latest'  # O usa windows-latest si lo prefieres

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: Maven@3
            displayName: 'Build con Maven'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              mavenVersionOption: 'Default'

          - task: CopyFiles@2
            displayName: 'Copiar JAR'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/target'
              Contents: '*.jar'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publicar Artefactos'
            inputs:
              artifactName: 'drop'
