options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    dir: '.'  # Asegúrate de que el archivo app.yaml esté en la raíz

timeout: 900s